SRCDIR = ..

# Test programs to compile, and a list of sources for each.
# To add a new test, put its name on the PROGS list
# and then add a name_SRC line that lists its source files.
PROGS = cat cmp cp echo halt hex-dump ls mcat mcp mkdir pwd rm shell \
	bubsort insult lineup matmult recursor DiningPhil Philosophers \
	DiningPhilM PhilosophersM ReadersWriters Reader Writer \
	ReadWriteM ReaderM WriterM BoundedBuffer Producer Consumer \
	BoundedBufferM ProducerM ConsumerM

# Should work from project 2 onward.
cat_SRC = cat.c
cmp_SRC = cmp.c
cp_SRC = cp.c
echo_SRC = echo.c
halt_SRC = halt.c
hex-dump_SRC = hex-dump.c
insult_SRC = insult.c
lineup_SRC = lineup.c
ls_SRC = ls.c
recursor_SRC = recursor.c
rm_SRC = rm.c

# Should work in project 3; also in project 4 if VM is included.
bubsort_SRC = bubsort.c
matmult_SRC = matmult.c
mcat_SRC = mcat.c
mcp_SRC = mcp.c

# Should work in project 4.
mkdir_SRC = mkdir.c
pwd_SRC = pwd.c
shell_SRC = shell.c

DiningPhil_SRC=DiningPhil.c
Philosophers_SRC=Philosophers.c
DiningPhilM_SRC=DiningPhilM.c
PhilosophersM_SRC=PhilosophersM.c

ReadersWriters_SRC=ReadersWriters.c
Reader_SRC=Reader.c
Writer_SRC=Writer.c

ReadWriteM_SRC=ReadWriteM.c
ReaderM_SRC=ReaderM.c
WriterM_SRC=WriterM.c

BoundedBuffer_SRC=BoundedBuffer.c
Producer_SRC=Producer.c
Consumer_SRC=Consumer.c

BoundedBufferM_SRC=BoundedBufferM.c
ProducerM_SRC=ProducerM.c
ConsumerM_SRC=ConsumerM.c

include $(SRCDIR)/Make.config
include $(SRCDIR)/Makefile.userprog


